### ISSUE TITLE
Probably obvious but can't make it work: foreign keys in custom transaction scope

### ISSUE THREAD

**Issue by tw-bert** [lsbardel/python-stdnet#62]
What's wrong with the following example code?
It's probably obvious, but i can't get it to work.
I can't use "with" syntax, because the actual code is part of an incoming data stream, so I have to begin and commit the transactions myself.
I also need (not shown in example code) to put multiple parents and their childs in one transaction.

```

import redis
from stdnet import odm

def testTrans():

  oRedis = redis.StrictRedis(host="srv-redis-dev-01", port=14111, db=1)
  oRedis.flushdb()

  models = odm.Router('redis://srv-redis-dev-01:14111?db=1')
  models.register(TestParent)  
  models.register(TestChild)
  session = models.session()

  session.begin()
  oCurrParent = models[TestParent](
    cName           = "SunflowerParent01",
    cTestParentAttr = "Seeds01")  
  session.add(oCurrParent)
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild01",
    cTestChildAttr = "Petals01")             
  session.add(oCurrChild)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild02",
    cTestChildAttr = "Petals02")             
  session.add(oCurrChild)
  print oCurrParent,oCurrChild,oCurrParent.children.all()
  session.commit()

  session.begin()
  oCurrParent = models[TestParent](
    cName           = "SunflowerParent02",
    cTestParentAttr = "Seeds02")  
  session.add(oCurrParent)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild03",
    cTestChildAttr = "Petals03")             
  session.add(oCurrChild)           
  print oCurrParent,oCurrChild
  session.commit()

class TestBase(odm.StdModel):
    cName    = odm.SymbolField(unique = True)
    def __unicode__(self):
        return self.cName
    class Meta:
        abstract = True

class TestParent(TestBase):
    cTestParentAttr = odm.CharField()

class TestChild(TestBase):
    oParent        = odm.ForeignKey(TestParent, related_name='children')
    cTestChildAttr = odm.CharField()

testTrans()

```

The following exception is thrown:

```

Traceback (most recent call last):
  File "E:\work\eclipse\11.1A\amber_python\src\amber\mxroot\mxflux\db_r\sc_mxflux_dfexport_r_idetest.py", line 66, in <module>
    testTrans()
  File "E:\work\eclipse\11.1A\amber_python\src\amber\mxroot\mxflux\db_r\sc_mxflux_dfexport_r_idetest.py", line 37, in testTrans
    session.commit()
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\session.py", line 608, in commit
    return self.transaction.commit()
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\session.py", line 453, in commit
    self.on_result = self._commit()
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\utils\async.py", line 76, in _
    return execute_generator(f(*args, **kwargs))
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\utils\async.py", line 40, in execute_generator
    result = gen.send(result)
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\session.py", line 470, in _commit
    multi.append(backend.execute_session(data))
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\backends\redisb\__init__.py", line 820, in execute_session
    json.dumps(instance._dbdata['errors']))
stdnet.utils.exceptions.FieldValueError: {"oParent_id": "Field 'oParent_id' is required for '__main__.testchild'."}
```

Different issue: what also surprises me, is that the transaction failed but isn't rolled back in the backend:

```
redis 127.0.0.1:14111[1]> keys *
1) "__main__.testparent:obj:1"
2) "__main__.testparent:ids"
3) "__main__.testparent:id"
4) "__main__.testparent:uni:cName"
```

Kind regards, tw

**Comment by lsbardel** [comment]
The foreign key needs the primary key of the model it is assigned to. In your example `TestParent` does not have an `id` because it is not persistent yet.
You have two options:
- First create `TestParent` and commit, than you can create and save `TestChild`.
- If you want to create them both in the same session, then `TestParent` must have an id which you supply.

For example:

```
class TestParent(TestBase):
    id = odm.SymbolField(primary_key=True)
    cTestParentAttr = odm.CharField()
```

A transaction commits what it can. In your example `TestParent` is saved correctly, only `TestChild` fails. Therefore the keys associated with the instance of `TestParent` are stored in redis.

**Comment by tw-bert** [comment]
Hi Luca,

Thank you very much, that solved it!

I could make the `cName` field in `TestBase` the primary key, that matches my original problem most. The field has a clearer name in that code, and is the unique identifier anyway.

I'll post another issue on the atomicity of transactions, and close this one.

Kind regards, tw

**Comment by tw-bert** [comment]
Hi Luca,

I reopened this issue because of beta 0.8.1.

My modified code (see below) runs fine in 0.8 on aix, but fails on 0.8.1b2 on windows with exception:

```
Traceback (most recent call last):
  File "E:\work\eclipse\11.1A\amber_python\src\amber\mxroot\mxflux\db_r\sc_mxflux_dfexport_r_idetest.py", line 66, in <module>
    testTrans()
  File "E:\work\eclipse\11.1A\amber_python\src\amber\mxroot\mxflux\db_r\sc_mxflux_dfexport_r_idetest.py", line 29, in testTrans
    cTestChildAttr = "Petals01")             
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\session.py", line 933, in __call__
    return self.model(*args, **kwargs)
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\models.py", line 23, in __init__
    field.set_value(self, kwargs.pop(field.name, None))
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\fields.py", line 644, in set_value
    setattr(instance, self.name, value)
  File "D:\Program Files\Program_Progs\Python\2.7\lib\site-packages\python_stdnet-0.8.1b2-py2.7-win32.egg\stdnet\odm\related.py", line 145, in __set__
    setattr(instance, self.field.attname, value.id)
AttributeError: 'TestParent' object has no attribute 'id'
```

Code that works on 0.8:

```
def testTrans():

  oRedis = redis.StrictRedis(host="srv-redis-dev-01", port=14111, db=2)
  oRedis.flushdb()

  models = odm.Router('redis://srv-redis-dev-01:14111?db=2')
  models.register(TestParent)  
  models.register(TestChild)
  session = models.session()

  session.begin()
  oCurrParent = models[TestParent](
    cName           = "SunflowerParent01",
    cTestParentAttr = "Seeds01")  
  session.add(oCurrParent)
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild01",
    cTestChildAttr = "Petals01")             
  session.add(oCurrChild)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild02",
    cTestChildAttr = "Petals02")             
  session.add(oCurrChild)
  print oCurrParent,oCurrChild,oCurrParent.children.all()
  session.commit()

  session.begin()
  oCurrParent = models[TestParent](
    cName           = "SunflowerParent02",
    cTestParentAttr = "Seeds02")  
  session.add(oCurrParent)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    cName          = "SunflowerChild03",
    cTestChildAttr = "Petals03")             
  session.add(oCurrChild)           
  print oCurrParent,oCurrChild
  session.commit()

class TestBase(odm.StdModel):
    cName    = odm.SymbolField(primary_key = True)
    def __unicode__(self):
        return self.cName
    class Meta:
        abstract = True

class TestParent(TestBase):
    cTestParentAttr = odm.CharField()

class TestChild(TestBase):
    oParent        = odm.ForeignKey(TestParent, related_name='children')
    cTestChildAttr = odm.CharField()

testTrans()
```

**Comment by tw-bert** [comment]
Hi Luca,

You can forget what I said about 0.8.1b2, if I rename the primary key to `id`, writing to redis works in both releases. I read elsewhere you prefer this for simplicity. I'm fine by that.

Here's the new code, with a simple query included for demonstration purposes. I missed something like this in the documentation.

```
def testTrans():

  oRedis = redis.StrictRedis(host="srv-redis-dev-01", port=14111, db=2)
  oRedis.flushdb()

  models = odm.Router('redis://srv-redis-dev-01:14111?db=2')
  models.register(TestParent)  
  models.register(TestChild)
  session = models.session()

  session.begin()
  oCurrParent = models[TestParent](
    id           = "SunflowerParent01",
    cTestParentAttr = "Seeds01")  
  session.add(oCurrParent)
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    id          = "SunflowerChild01",
    cTestChildAttr = "Petals01")             
  session.add(oCurrChild)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    id          = "SunflowerChild02",
    cTestChildAttr = "Petals02")             
  session.add(oCurrChild)
  print oCurrParent,oCurrChild
  session.commit()

  session.begin()
  oCurrParent = models[TestParent](
    id           = "SunflowerParent02",
    cTestParentAttr = "Seeds02")  
  session.add(oCurrParent)           
  oCurrChild = models[TestChild](
    oParent        = oCurrParent,
    id          = "SunflowerChild03",
    cTestChildAttr = "Petals03")             
  session.add(oCurrChild)           
  print oCurrParent,oCurrChild
  session.commit()

  return models

def testQuery(models=None):

  if models == None:
    oRedis = redis.StrictRedis(host="srv-redis-dev-01", port=14111, db=2)
    oRedis.flushdb()
    models = odm.Router('redis://srv-redis-dev-01:14111?db=2')
    models.register(TestParent)  
    models.register(TestChild)

  testparents = models[TestParent].query()  
  print list(testparents)

class TestBase(odm.StdModel):
    def __unicode__(self):
        return self.id
    class Meta:
        abstract = True

class TestParent(TestBase):
    id              = odm.SymbolField(primary_key = True)
    cTestParentAttr = odm.CharField()

class TestChild(TestBase):
    id             = odm.SymbolField(primary_key = True)
    oParent        = odm.ForeignKey(TestParent, related_name='children')
    cTestChildAttr = odm.CharField()


testQuery(testTrans())
```

Which results in:

```
SunflowerParent01 SunflowerChild02
SunflowerParent02 SunflowerChild03
[TestParent: SunflowerParent01, TestParent: SunflowerParent02]
```

(tested on unix and windows)
If you don't want to write anything to redis, query it with:

change

```
testQuery(testTrans())
```

into

```
testQuery()
```

and get:

```
[TestParent: SunflowerParent01, TestParent: SunflowerParent02]
```

which is what we wrote previously.
